
title: "PROBPROG | International Conference on Probabilistic Programming"
url: http://probprog-conference.github.io
timezone: America/New_York

navigation:
- text: Announcement
  url: /call/
- text: Agenda
  url: /agenda/
- text: Conduct
  url: /conduct/
- text: Archive
  url: /archive/
