name: "PROBPROG 2020"
url: http://probprog-conference.github.io
#baseurl: /
permalink: /:year/:month/:day/:title
timezone: America/New_York

navigation:
- text: Program
  url: /program/
- text: Conduct
  url: /conduct/
- text: 2018
  url: /2018/
