
title: "PROBPROG | International Conference on Probabilistic Programming"
url: http://probprog-conference.github.io
timezone: America/New_York

navigation:
- text: Home
  url: /
- text: Call
  url: /call/
- text: Agenda
  url: /agenda/
- text: Attend
  url: /attend/
- text: Conduct
  url: /conduct/
- text: Archive
  url: /archive/
